### ISSUE TITLE
How to add midi notes per channel?

### ISSUE THREAD

**Issue by pabloriera** [fand/veda#100]
Hi, I was wondering if it is possible to add that feature. I was looking up in the code but I couldn't find where the midi sampler2D are managed.

Amazing work on veda!

**Comment by fand** [comment]
thanks @pabloriera !

MIDI events are processed in VEDA.js repository.
VEDA.js is separated from VEDA main repository because we want to use VEDA engine on websites.
https://github.com/fand/vedajs/blob/master/src/midi-loader.ts#L66-L72

VEDA.js processes MIDI notes from all channels, so currently we can't tell which channel notes are from.
Maybe we can implement MIDI channel selector after #96 is merged, but idk when it will be 😅

**Comment by pabloriera** [comment]
Apparently I didn't search well, haha. I will check if I could manage to separate the channels. Thanks

**Comment by pabloriera** [comment]
Hi, I am new to Atom. How could I edit vedajs and make veda package to run with the edited version?

**Comment by fand** [comment]
You can run fork of veda with `yarn link` and `apm link` 🐰 
(`yarn link` is similar to `npm link` but we recommend using yarn in veda)

1. Go to vedajs directory run `yarn link`
2. Go to veda directory run `yarn link vedajs && apm link`
3. Restart Atom

then your Atom will load your fork of VEDA.
ref. https://veda.gl/contributing/#1-fork-clone-fand-vedajs

**Comment by pabloriera** [comment]
Oh! I didn't see the contributing page! I got it working! Thanks. 

Atom should have a way up updating its dev-packages without restart :satisfied:
